# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6abc018c21e66157915800e1333782783522b6ad8df8ef25d1c1dbff392ef3869cef96aa441403b089dceba05f6bc1cd50623564cef298fe8ea9e470cfa2141

test:
  secret_key_base: e2c45740bd86cba0f15f64fa19580274ed3377b68074e0c794e68f8b5381ce011ce8c96debdc6bd7246a3103bf6c7913ad77a23e7eb39d6c11f568187e3ab519

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
